<a href="https://colab.research.google.com/github/Luna7891/tibame1224/blob/main/03_02_Pandas_%E8%AA%B2%E5%A0%82%E7%B7%B4%E7%BF%92.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

* 完成後請寄到EMAIL : clement.class.02@gmail.com
* 信件主旨請設定為： 03-02.Pandas_課堂練習_學號_姓名 (例: "03-02.Pandas_課堂練習_00_陳仁政")
* 附件檔名請設定為： 03-02.Pandas_課堂練習_學號_姓名.ipynb (例: "03-02.Pandas_課堂練習_00_陳仁政.ipynb")

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
data = pd.read_csv("/content/drive/MyDrive/data/vgsales.csv")
data.head()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37

In [7]:
# 找出有缺失值的欄位
data.isnull().sum()

Rank              0
Name              0
Platform          0
Year            271
Genre             0
Publisher        58
NA_Sales          0
EU_Sales          0
JP_Sales          0
Other_Sales       0
Global_Sales      0
dtype: int64

In [8]:
# 計算欄位的基本統計數據
data.describe()

,Rank,Year,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
count,16598.000000,16327.000000,16598.000000,16598.000000,16598.000000,16598.000000,16598.000000
mean,8300.605254,2006.406443,0.264667,0.146652,0.077782,0.048063,0.537441
std,4791.853933,5.828981,0.816683,0.505351,0.309291,0.188588,1.555028
min,1.000000,1980.000000,0.000000,0.000000,0.000000,0.000000,0.010000
25%,4151.250000,2003.000000,0.000000,0.000000,0.000000,0.000000,0.060000
50%,8300.500000,2007.000000,0.080000,0.020000,0.000000,0.010000,0.170000
75%,12449.750000,2010.000000,0.240000,0.110000,0.040000,0.040000,0.470000
max,16600.000000,2020.000000,41.490000,29.020000,10.220000,10.570000,82.740000

In [9]:
# 取出 "Publisher" 欄位的資料
data["Publisher"]

0          Nintendo
1          Nintendo
2          Nintendo
3          Nintendo
4          Nintendo
            ...
16593         Kemco
16594    Infogrames
16595    Activision
16596      7G//AMES
16597       Wanadoo
Name: Publisher, Length: 16598, dtype: object

In [10]:
# 取出 Publisher, Name, Genre 欄位的資料
data[["Publisher","Name","Genre"]]

,Publisher,Name,Genre
0,Nintendo,Wii Sports,Sports
1,Nintendo,Super Mario Bros.,Platform
2,Nintendo,Mario Kart Wii,Racing
3,Nintendo,Wii Sports Resort,Sports
4,Nintendo,Pokemon Red/Pokemon Blue,Role-Playing
...,...,...,...
16593,Kemco,Woody Woodpecker in Crazy Castle 5,Platform
16594,Infogrames,Men in Black II: Alien Escape,Shooter
16595,Activision,SCORE International Baja 1000: The Official Game,Racing
16596,7G//AMES,Know How 2,Puzzle
16597,Wanadoo,Spirits & Spells,Platform

In [11]:
# 計算每筆資料的 NA_Sales,EU_Sales,JP_Sales,Other_Sales 總和

# data["NA_Sales"] + data["EU_Sales"] + data["JP_Sales"] + data["Other_Sales"]

data[["NA_Sales","EU_Sales","Other_Sales"]].sum(axis=1)

0        78.97
1        33.43
2        32.04
3        29.72
4        21.16
         ...
16593     0.01
16594     0.01
16595     0.00
16596     0.01
16597     0.01
Length: 16598, dtype: float64

In [12]:
# 計算每筆資料的 NA_Sales,EU_Sales,JP_Sales,Other_Sales 總和，並存入新的欄位"總和"
data['總和'] = data[["NA_Sales","EU_Sales","Other_Sales"]].sum(axis=1)
data

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,總和
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74,78.97
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,33.43
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82,32.04
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00,29.72
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,21.16
...,...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01,0.00
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01,0.01

In [13]:
#找出發行商為Nintendo的遊戲名稱

data[data["Publisher"] == "Nintendo"]

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,總和
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74,78.97
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,33.43
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82,32.04
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00,29.72
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,21.16
...,...,...,...,...,...,...,...,...,...,...,...,...
16269,16272,Slide Adventure: Mag Kid,DS,2007.0,Action,Nintendo,0.00,0.00,0.01,0.00,0.01,0.00
16357,16360,Mario vs. Donkey Kong: Tipping Stars,WiiU,2015.0,Puzzle,Nintendo,0.00,0.00,0.01,0.00,0.01,0.00
16456,16459,Art Academy: Home Studio,WiiU,2015.0,Misc,Nintendo,0.00,0.00,0.01,0.00,0.01,0.00
16473,16476,Captain Rainbow,Wii,2008.0,Adventure,Nintendo,0.00,0.00,0.01,0.00,0.01,0.00
16542,16545,Mario & Luigi: Paper Jam & Mario Kart 7 Double...,3DS,2015.0,Misc,Nintendo,0.00,0.00,0.01,0.00,0.01,0.00

In [14]:
data[data["Publisher"] == "Nintendo"]["Name"].unique().size

667

In [15]:
#列出所有Wii的遊戲名稱
data[data["Platform"] == "Wii"]["Name"]

0                                               Wii Sports
2                                           Mario Kart Wii
3                                        Wii Sports Resort
7                                                 Wii Play
8                                New Super Mario Bros. Wii
                               ...
16517                         Teenage Mutant Ninja Turtles
16552             Mahou Sensei Negima!? Neo-Pactio Fight!!
16573                                  Mini Desktop Racing
16574    Yattaman Wii: BikkuriDokkiri Machine de Mou Ra...
16581                                            Fit & Fun
Name: Name, Length: 1325, dtype: object

In [16]:
#計算所有GBA遊戲的銷售總合
data[data["Platform"] == "GBA"]["Global_Sales"].sum()

318.5

In [17]:
#計算任天堂運動類遊戲的銷售總量

c1 = data['Publisher'] == 'Nintendo'
c2 = data['Genre'] == 'Sports'
data[c1 & c2]['Global_Sales'].sum()

#data[data["Genre"] == "Sports"][data["Publisher"] == "Nintendo"]["Global_Sales"].sum()

data[(data["Genre"] == "Sports") & (data["Publisher"] == "Nintendo")]["Global_Sales"].sum()

218.01

In [18]:
#列出北美地區銷售量最高的前五名遊戲
# index = data["NA_Sales"].sort_values(ascending=False).index[0:5]
# data.iloc[index]

data.sort_values(by='NA_Sales',ascending=False).head(5)

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,總和
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74,78.97
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,33.43
9,10,Duck Hunt,NES,1984.0,Shooter,Nintendo,26.93,0.63,0.28,0.47,28.31,28.03
5,6,Tetris,GB,1989.0,Puzzle,Nintendo,23.20,2.26,4.22,0.58,30.26,26.04
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82,32.04

In [19]:
#列出北美與歐洲地區銷售量總和最高的前五名遊戲
#北美+EU

temp_col = data["NA_Sales"] + data["EU_Sales"]
index = temp_col.sort_values(ascending=False).index[0:5]
data.iloc[index]

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,總和
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74,78.97
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,33.43
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82,32.04
9,10,Duck Hunt,NES,1984.0,Shooter,Nintendo,26.93,0.63,0.28,0.47,28.31,28.03
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00,29.72

In [20]:
#找出總共有多少種不同的平台
data["Platform"].unique().size

31

In [21]:
#寫程式計算不同平台的總銷售量
for plat in data["Platform"].unique():
  print(plat,round(data[data["Platform"] == plat]["Global_Sales"].sum(),2))

Wii 926.71
NES 251.07
GB 255.45
DS 822.49
X360 979.96
PS3 957.84
PS2 1255.64
SNES 200.05
GBA 318.5
3DS 247.46
PS4 278.1
N64 218.88
PS 730.66
XB 258.26
PC 258.82
2600 97.08
PSP 296.28
XOne 141.06
GC 199.36
WiiU 81.86
GEN 28.36
DC 15.97
PSV 61.93
SAT 33.59
SCD 1.87
WS 1.42
NG 1.44
TG16 0.16
3DO 0.1
GG 0.04
PCFX 0.03

In [22]:
# 使用GroupBy來完成上述的工作
data.groupby("Platform")["Global_Sales"].sum()

Platform
2600      97.08
3DO        0.10
3DS      247.46
DC        15.97
DS       822.49
GB       255.45
GBA      318.50
GC       199.36
GEN       28.36
GG         0.04
N64      218.88
NES      251.07
NG         1.44
PC       258.82
PCFX       0.03
PS       730.66
PS2     1255.64
PS3      957.84
PS4      278.10
PSP      296.28
PSV       61.93
SAT       33.59
SCD        1.87
SNES     200.05
TG16       0.16
WS         1.42
Wii      926.71
WiiU      81.86
X360     979.96
XB       258.26
XOne     141.06
Name: Global_Sales, dtype: float64